\hypertarget{classsql__exception}{}\doxysection{sql\+\_\+exception Class Reference}
\label{classsql__exception}\index{sql\_exception@{sql\_exception}}


SQL文の実行に失敗したときに発生する例外クラス  




{\ttfamily \#include $<$sql\+\_\+exception.\+hpp$>$}

Inheritance diagram for sql\+\_\+exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classsql__exception}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classsql__exception_aa24997092f8f253ea7479d0e69d6b3f4}\label{classsql__exception_aa24997092f8f253ea7479d0e69d6b3f4}} 
{\bfseries sql\+\_\+exception} (string message)
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
SQL文の実行に失敗したときに発生する例外クラス 

基本的に防ぎようがない、一旦これの発生は考慮しないことにしてもいいかもしれない 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kowerkoint/\+Documents/\+GUIApp\+\_\+\+Team\+Dev2021/sql\+\_\+exception.\+hpp\end{DoxyCompactItemize}
